### PR TITLE
fix: alias name kko to FCA in get_correlator_inputs

### PR DESCRIPTION
**Pull request by aelanman**
Querying the layout db for "KKO" or "kko" should return the KKO inputs. Currently only accepting pco.

Also adds support for GBO.

### CODE REVIEW

**Comment by aaronpearlman** [comment]
Looks good

**Comment by aaronpearlman** [comment]
Apparently, I don't have write access to be able to approve the PR for merging... Tagging @jrs65

**Review by aaronpearlman — APPROVED** [review]

**Comment by aaronpearlman** [comment]
@aelanman I think you can merge this PR into the `master` branch

**Comment by aelanman** [comment]
Thanks @aaronpearlman

**Pull request merged**
