### PR TITLE
Add end times to static masking

### PR DESCRIPTION
**Pull request by ljgray**
Add specification of end times for static rfi masking so we can unmask a band if the rfi source shuts off. 

I haven't actually updated the list of bad frequencies with known end times yet.

### CODE REVIEW

**Review by hgan0 — APPROVED** [review]
Thanks for adding the end time to the mask. It looks good to me. 
Should we also update the bad frequency list here?

**Comment by jrs65** [comment]
Sweet, I was just thinking of doing this.

You might as well add the end times for those bands in there while you're on. Let me just go and dig into those spectrum plots to figure them out and I'll post them here.

**Comment by jrs65** [comment]
End dates:

- TV channel 27 (548–554 MHz): 2022-08-24
- TV channel 32 (578–584 MHz): 2022-08-25

They're both definitely gone by midnight UTC on those dates,

**Comment by ljgray** [comment]
@jrs65 I've added those bands, which end on CSD 3212 and 3213 (inclusive) respectively (i.e. the first good day for the bands are 3213 and 3214). If you can just sanity check me on those then I'll merge it

**Pull request merged**
