### PR TITLE
ci(docs): move to github-pages

### PR DESCRIPTION
**Pull request by nritsche**
https://chime-experiment.github.io/ch_util/index.html

### CODE REVIEW

**Comment by jrs65** [comment]
The version at that link is ancient. I guess it won't get updated until this is merged?

**Comment by nritsche** [comment]
> The version at that link is ancient. I guess it won't get updated until this is merged?

It's actually generated by this PR. What's missing?

**Comment by jrs65** [comment]
I guess I was basing that mostly on the listed version which is `0+untagged.1.g439c638`

**Comment by jrs65** [comment]
Hmmm.... that seems to be because the tags weren't repointed when the history was rewritten. Maybe that's why the old history and password could still be found.

**Comment by nritsche** [comment]
> Hmmm.... that seems to be because the tags weren't repointed when the history was rewritten. Maybe that's why the old history and password could still be found.

I updated the tags. The docs still show that untagged version string, but github pages might just be slow to update...

**Comment by nritsche** [comment]
the github action for checkout needed to be forced to fetch tags. It works now. @jrs65

**Review by jrs65 — APPROVED** [review]

**Pull request merged**
